### ISSUE TITLE
ImportError: No module named 'coincurve'

### ISSUE THREAD

**Issue by vivosmith** [ofek/bit#11]
When I go to run a program based on this, I get:
Traceback (most recent call last):
  File "C:\Users\***\Desktop\bit-master\bitcoin2.py", line 1, in <module>
    from bit import Key
  File "C:\Users\***\Desktop\bit-master\bit\__init__.py", line 1, in <module>
    from bit.format import verify_sig
  File "C:\Users\***\Desktop\bit-master\bit\format.py", line 2, in <module>
    from coincurve import *
ImportError: No module named 'coincurve'

The problem is I imported coincurve directly into my folder as well as installing it with pip. Further I tried to look for verify_sig anywhere and could not find it.

**Comment by ofek** [comment]
@vivosmith Are you sure you are using Python 3.5+?

**Comment by vivosmith** [comment]
Yes. Made sure.

**Comment by vivosmith** [comment]
C:\Users\*\Desktop\bit-master>bitcoin2.py
Traceback (most recent call last):
  File "C:\Users\*\Desktop\bit-master\bitcoin2.py", line 1, in <module>
    from bit import Key
  File "C:\Users\*\Desktop\bit-master\bit\__init__.py", line 1, in <module>
    from bit.format import verify_sig
  File "C:\Users\*\Desktop\bit-master\bit\format.py", line 1, in <module>
    from coincurve import verify_signature as _vs
ImportError: No module named 'coincurve'

**Comment by vivosmith** [comment]
Offending code:
`from bit import Key
my_key = Key(...)
my_key.get_balance('usd')


outputs = [
 # Wikileaks
('1HB5XMLmzFVj8ALj6mfBsbifRoD4miY36v', 0.0035, 'btc'),
# Internet Archive
('1Archive1n2C579dMsAu3iC6tWzuQJz8dN', 190, 'jpy'),
# The Pirate Bay
('129TQVAroeehD9fZpzK51NdZGQT4TqifbG', 3, 'eur'),
# xkcd
('14Tr4HaKkKuC1Lmpr2YMAuYVZRWqAdRTcr', 2.5, 'cad')
 ]

# my_key.send(outputs)
`

I just wanted to test the balance (which is zero). But even that would not work.

**Comment by ofek** [comment]
What was your install command?

**Comment by vivosmith** [comment]
I tried pip & pip3 install bit 
and
I tried pip & pip3 install coincurve

**Comment by ofek** [comment]
Try `python3 bitcoin2.py`

**Comment by vivosmith** [comment]
Weird. For whatever reason python3 does not work, but python does. I think that cleared it up. I have never had to enter python before opening a script, however it could be conflicting versions I have that I forgot about. I am testing the balance right now to see if it works. Was the coincurve issue related to specific code for a specific version?

**Comment by ofek** [comment]
The issue is your default application for .py files is not the same Python that is on PATH.

**Comment by Sidaretta** [comment]
Hi
I install lit package for litecoin on python 3.6.2 it installed sucessfully, but when I import package, shows me a error to install coincurve package, then I install this sucessfully, after that, I can't import lit package, it shows me this error:
>>> import lit
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import lit
  File "C:\Program Files\Python 3.6.2\lib\lit\__init__.py", line 1, in <module>
    from lit.format import verify_sig
  File "C:\Program Files\Python 3.6.2\lib\lit\format.py", line 1, in <module>
    from coincurve import verify_signature as _vs
  File "C:\Program Files\Python 3.6.2\lib\coincurve\__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "C:\Program Files\Python 3.6.2\lib\coincurve\context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "C:\Program Files\Python 3.6.2\lib\coincurve\flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ModuleNotFoundError: No module named 'coincurve._libsecp256k1'
how can I fix this?

**Comment by bjarnemagnussen** [comment]
This is the Github of the `bit` project and I don't know of the `lit` project. It would probably be better to ask this question at their project page.
