### ISSUE TITLE
Transaction broadcast failed, or Unspents were already used

### ISSUE THREAD

**Issue by wiomka** [ofek/bit#110]
Hi. I can't send my funds to another address because constantly getting an follow errors

```
>>> tx = m.send([('...', 0.131, 'btc')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.pyenv/btc_wallet/lib/python3.6/site-packages/bit/wallet.py", line 566, in send
    NetworkAPI.broadcast_tx_testnet(tx_hex)
  File "/home/.pyenv/btc_wallet/lib/python3.6/site-packages/bit/network/services.py", line 442, in broadcast_tx_testnet
    raise ConnectionError('Transaction broadcast failed, or '
ConnectionError: Transaction broadcast failed, or Unspents were already used.
```

```
>>> m.get_balance('usd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.pyenv/btc_wallet/lib/python3.6/site-packages/bit/wallet.py", line 460, in get_balance
    self.get_unspents()
  File "/home/.pyenv/btc_wallet/lib/python3.6/site-packages/bit/wallet.py", line 468, in get_unspents
    self.unspents[:] = NetworkAPI.get_unspent_testnet(self.address)
  File "/home/.pyenv/btc_wallet/lib/python3.6/site-packages/bit/network/services.py", line 395, in get_unspent_testnet
    raise ConnectionError('All APIs are unreachable.')
ConnectionError: All APIs are unreachable.
```

What I can do for solve these errors?

**Comment by bjarnemagnussen** [comment]
I think that currently all testnet APIs are offline. I have an open PR (#96) that should fix it. 

In the meantime if you have the possibility to run your own node you can connect to it with bit (https://github.com/ofek/bit/blob/7d933640f43c697cd0ccfa413262e278401eaa87/bit/network/services.py#L439).

**Comment by wiomka** [comment]
thanks

**Comment by AlmCoding** [comment]
Hmm I have had the same issue today on the mainnet.
```
  File "send_bitcoins.py", line 104, in <module>
    NetworkAPI.broadcast_tx_testnet(transaction)
  File "/home/alexander/miniconda3/envs/py38/lib/python3.8/site-packages/bit/network/services.py", line 1250, in broadcast_tx_testnet
    raise ConnectionError('Transaction broadcast failed, or Unspents were already used.')
ConnectionError: Transaction broadcast failed, or Unspents were already used.
```

When posting the transaction after signing on [https://www.blockchain.com/btc/pushtx](url) it went trough...

**Comment by bjarnemagnussen** [comment]
Just to be really sure, you are on mainnet? Because the error message shows it as if you try to send the transaction using testnet.

**Comment by AlmCoding** [comment]
Sorry, my bad. You are right, I took the wrong function  :sweat_smile:
