### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by khertan** [ofek/bit#3]
Hi,

Just to test your lib and how it s handle error and refuse from service use to get balance, i just executed the following code, once you reach quota limit of services API the error appear.

```python
>>> import bit
>>> while True:
...   k = bit.Key()
...   if k.get_balance() != '0':
...     print(k.to_wif())
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/bit/wallet.py", line 190, in get_balance
    self.get_unspents()
  File "/usr/local/lib/python3.5/dist-packages/bit/wallet.py", line 198, in get_unspents
    self.unspents[:] = NetworkAPI.get_unspent(self.address)
  File "/usr/local/lib/python3.5/dist-packages/bit/network/services.py", line 421, in get_unspent
    return api_call(address)
  File "/usr/local/lib/python3.5/dist-packages/bit/network/services.py", line 41, in get_unspent
    for tx in r.json()
  File "/usr/local/lib/python3.5/dist-packages/bit/network/services.py", line 41, in <listcomp>
    for tx in r.json()
TypeError: string indices must be integers```

**Comment by ofek** [comment]
Thanks! This is fixed in master.

Though, what you are attempting is definite abuse of the services. Please also keep in mind you'll be in that loop for millions of years before anything is printed!

**Comment by khertan** [comment]
Of course that's an abuse, that's was just a sample test. I got the error the first time after the 80th requests just by watching keys I use, I added a ratio timer just for my own use.

Else not sure millions is enough years :) some have calculate 10^80

**Comment by ofek** [comment]
Yes, thanks for testing this!
