### ISSUE TITLE
ImportError: Library not loaded: Reason: image not found

### ISSUE THREAD

**Issue by MannyKuflik** [ofek/bit#37]
I have tried running a simple code to check my testnet balance, but it isn't working.
Here is my code:
<img width="542" alt="screen shot 2018-07-02 at 4 09 37 pm" src="https://user-images.githubusercontent.com/39571252/42168828-5ad92d74-7e12-11e8-9fca-4f17b45342e2.png">

I when i run "python BTCt.py" or "python3 BTC.py" the following error is thrown:

Traceback (most recent call last):
  File "BTCt.py", line 1, in <module>
    from bit.network.services import SmartBitAPI
  File "/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/bit/__init__.py", line 1, in <module>
    from bit.format import verify_sig
  File "/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/bit/format.py", line 1, in <module>
    from coincurve import verify_signature as _vs
  File "/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/MannyKuflik/Library/Python/3.6/lib/python/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so
  Reason: image not found

Please help

**Comment by teran-mckinney** [comment]
How did you install bit?

**Comment by MannyKuflik** [comment]
I did pip install bit and pip3 install bit and also tried doing it in a virtual environment

**Comment by MannyKuflik** [comment]
Nevermind, I somehow fixed it by running "brew install gmp"
