### ISSUE TITLE
[Error] send btc with testnet

### ISSUE THREAD

**Issue by henrytom1703** [ofek/bit#66]
```
wifi_key_from = "cNTgUJtZYxK4iC2wDxLxSityGtqWyDLUnJbg2ESWgmUZ63z6eFzG"
address_from = "motaaTUVLRTSVXQo9RUMTxJEX6BACZ8WGo"
to_address = "mvsPR91C29sQzoXiAJaod8s1XneMJKYB6U"
to_wifi = "cNGfoMaD7Aer7mUpDch8KWwMv4yqZLQT318DaWzYLQTQij8Bw1ct"

from bit import Key, PrivateKey, PrivateKeyTestnet

my_key = PrivateKeyTestnet(wifi_key_from)
print(my_key.address)
print(my_key.get_balance('btc'))

to_add = PrivateKeyTestnet(to_wifi)
print(to_add.address)
print(to_add.get_balance('btc'))

outputs = [
(to_add, 0.0001, 'btc')
]

# print(my_key.get_unspents())
tx = my_key.send(outputs)
print(tx)
```

```
motaaTUVLRTSVXQo9RUMTxJEX6BACZ8WGo
0.09786592
mvsPR91C29sQzoXiAJaod8s1XneMJKYB6U
0
Traceback (most recent call last):
  File "/home/tomtony/sourcecode/fx001/backend/TestH7.py", line 24, in <module>
    tx = my_key.send(outputs)
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/wallet.py", line 722, in send
    unspents=unspents
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/wallet.py", line 674, in create_transaction
    version=self.version
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/transaction.py", line 446, in sanitize_tx_data
    output_size = [len(address_to_scriptpubkey(o[0])) + 9 for o in outputs]
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/transaction.py", line 446, in <listcomp>
    output_size = [len(address_to_scriptpubkey(o[0])) + 9 for o in outputs]
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/transaction.py", line 476, in address_to_scriptpubkey
    get_version(address)
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/format.py", line 38, in get_version
    version, _ = bech32_decode(address)
  File "/home/tomtony/python_env/fx-env/lib/python3.6/site-packages/bit/base32.py", line 63, in bech32_decode
    if ((any(ord(x) < 33 or ord(x) > 126 for x in bech)) or
TypeError: 'PrivateKeyTestnet' object is not iterable

Process finished with exit code 1
```

**Comment by bjarnemagnussen** [comment]
You are referencing the `PrivateKeyTestnet` object `to_add` inside your list of tuples called `outputs`. However you must use the address, e.g.:
```python
outputs = [
(to_add.address, 0.0001, 'btc')
]
```

Also notice that Bit supports Segwit and you can find the corresponding P2SH-nested Segwit address for a `PrivateKey` object by calling the `segwit_address` property on it.

You can find the documention here:
https://ofek.github.io/bit/
