### ISSUE TITLE
unable to import bit due to syntax error

### ISSUE THREAD

**Issue by cythrauL** [ofek/bit#77]
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bit import Key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\bit\__init__.py", line 1, in <module>
  File "build\bdist.win32\egg\bit\format.py", line 3, in <module>
  File "C:\Python27\lib\site-packages\bit-0.5.2-py2.7.egg\bit\base58.py", line 53
    'character.'.format(char)) from None

**Comment by cythrauL** [comment]
closed, doesn't support python2.
